micronaut:
  application:
    name: auth-service
  server:
    port: ${AUTH_SERVICE_PORT}
    cors:
      enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET}
              base64: false
        generator:
          access-token:
            expiration: 86400 # 24 hours

datasources:
  default:
    url: ${DATABASE_URL}
    driver-class-name: ${DATABASE_DRIVER}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    dialect: H2

jpa:
  default:
    entity-scan:
      packages: 'com.armadoon.homebuddy.auth.entity'
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

logger:
  levels:
    com.armadoon.homebuddy.auth: DEBUG
    io.micronaut.data: DEBUG
    io.micronaut.security: DEBUG
    org.hibernate.SQL: DEBUG
    root: WARN

endpoints:
  all:
    enabled: false
  health:
    enabled: true
    sensitive: false