micronaut:
  application:
    name: auth-service
  security:
    enabled: false
  server:
    port: 8081
    cors:
      enabled: true

datasources:
  default:
    url: jdbc:h2:mem:testDb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true
        format_sql: true

logger:
  levels:
    com.armadoon.homebuddy.auth: DEBUG
    io.micronaut.data: DEBUG
    io.micronaut.security: DEBUG
    root: WARN

endpoints:
  all:
    enabled: false
  health:
    enabled: true
    sensitive: false