micronaut:
  application:
    name: auth-service
  server:
    port: ${AUTH_SERVICE_PORT:8081}
    cors:
      enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET:dev-jwt-secret-for-local-development-only-change-in-production}
              base64: false
        generator:
          access-token:
            expiration: 86400 # 24 hours

datasources:
  default:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/homebuddy}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
      packages: 'com.armadoon.homebuddy.auth.entity'
    properties:
      hibernate:
        hbm2ddl:
          auto: validate  # Flyway řídí schéma
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true
      validate-on-migrate: true

logger:
  levels:
    com.armadoon.homebuddy.auth: DEBUG
    io.micronaut.data: DEBUG
    io.micronaut.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG
    root: INFO

endpoints:
  all:
    enabled: false
  health:
    enabled: true
    sensitive: false
    details-visible: anonymous