version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: homebuddy
      POSTGRES_USER: homebuddy
      POSTGRES_PASSWORD: homebuddy123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/homebuddy
      - DB_USERNAME=homebuddy
      - DB_PASSWORD=homebuddy123
      - MICRONAUT_ENVIRONMENTS=docker
    depends_on:
      - postgres
    volumes:
      - ./shared/openapi-specs:/app/api-specs

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - MICRONAUT_ENVIRONMENTS=docker
    depends_on:
      - auth-service

volumes:
  postgres_data: